eureka:
  instance:
    ip-address: 127.0.01
    prefer-ip-address: true
spring:
  zipkin:
    base-url: http://106.14.163.235:9411
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 47.100.138.93
    port: 5672
    username: tanjun
    password: 123456
  datasource:
     name: dev
     url: jdbc:mysql://47.100.138.93:3306/snailmall
     username: root
     password: 123456
redis:
    host: 47.100.138.93
    port: 6379
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000
zk:
  host: 111.231.119.253
